### ISSUE TITLE
env file cleanup

### ISSUE THREAD

**Issue by bospoort** [digitalaidseattle/das-admin-template#38]
Can we remove unnecessary files and unnecessary entries from the env files? It is currently confusing as to what is needed. We can also comment out lines from the files that are potentially needed in the future (with appropriate comments). 

If env files are needed for specific uses, it should be documented somewhere. 

AC:
- only required env files are in the template
- all env files are documented

**Comment by jnakaso** [comment]
Whether we like it or not, DAS has the Task Group/Task Detail system to track issues.  This issue should be moved there so that it can be tracked as evaluated along side other DAS concerns.
